### create bitly
POST http://localhost:7000/bitly
Accept: application/json
Content-Type: application/json

{
    "longlink":"https://facabook.com/"
}
###
GET http://localhost:7000/bitly/bitly8
Accept: application/json